name: Vercel Function Deployment

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "apps/profiler/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: install Vercel CLI
        run: npm install --global vercel@latest && vercel link apps/profiler --repo --yes --cwd=apps/profiler --token=${{ secrets.VERCEL_TOKEN }}
      - name: Install Dependencies
        run: pnpm install --filter=profiler --no-frozen-lockfile
      - name: pull Vercel environment information
        run: vercel pull --yes --environment=production --cwd=apps/profiler --token=${{ secrets.VERCEL_TOKEN }}
      - name: build project artifacts
        run: vercel build --prod --cwd=apps/profiler --token=${{ secrets.VERCEL_TOKEN }}
      - name: deploy project artifacts to Vercel
        run: vercel deploy --prebuilt --prod --cwd=apps/profiler --token=${{ secrets.VERCEL_TOKEN }}
