type Operator = {
	name: string;
	safename: string;
	roles: string[];
	side: string;
	icon: string;
};

export const UbisoftOperatorConfig: Record<string, Operator> = {
	deimos: {
		name: 'Deimos',
		safename: 'deimos',
		roles: ['Intel', 'Front Line'],
		side: 'attacker',
		icon: 'https://i.imgur.com/av1keWp.png',
	},
	tubarao: {
		name: 'Tubarão',
		safename: 'tubarao',
		roles: ['Anti-Entry', 'Anti-Gadget'],
		side: 'defender',
		icon: 'https://i.imgur.com/UdpHcJv.png',
	},
	ram: {
		name: 'Ram',
		safename: 'ram',
		roles: ['Breach'],
		side: 'attacker',
		icon: 'https://i.imgur.com/NokDK0I.png',
	},
	fenrir: {
		name: 'Fenrir',
		safename: 'fenrir',
		roles: ['Trapper', 'Crowd Control'],
		side: 'defender',
		icon: 'https://i.imgur.com/6T16oPJ.png',
	},
	brava: {
		name: 'Brava',
		safename: 'brava',
		roles: ['Intel', 'Anti-Gadget'],
		side: 'attacker',
		icon: 'https://i.imgur.com/1Se82ke.png',
	},
	solis: {
		name: 'Solis',
		safename: 'solis',
		roles: ['Intel', 'Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/PgtffOh.png',
	},
	grim: {
		name: 'Grim',
		safename: 'grim',
		roles: ['Front Line', 'Map Control'],
		side: 'attacker',
		icon: 'https://i.imgur.com/dV5ilwv.png',
	},
	sens: {
		name: 'Sens',
		safename: 'sens',
		roles: ['Support', 'Map Control'],
		side: 'attacker',
		icon: 'https://i.imgur.com/kwfMIVz.png',
	},
	azami: {
		name: 'Azami',
		safename: 'azami',
		roles: ['Support', 'Anti-Entry'],
		side: 'defender',
		icon: 'https://i.imgur.com/QnqklyT.png',
	},
	thorn: {
		name: 'Thorn',
		safename: 'thorn',
		roles: ['Anti-Entry', 'Trapper'],
		side: 'defender',
		icon: 'https://i.imgur.com/w5DB6xs.png',
	},
	osa: {
		name: 'Osa',
		safename: 'osa',
		roles: ['Intel', 'Support'],
		side: 'attacker',
		icon: 'https://i.imgur.com/odZHbem.png',
	},
	thunderbird: {
		name: 'Thunderbird',
		safename: 'thunderbird',
		roles: ['Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/21vn9y7.png',
	},
	flores: {
		name: 'Flores',
		safename: 'flores',
		roles: ['Anti-Gadget', 'Intel'],
		side: 'attacker',
		icon: 'https://i.imgur.com/1wBdB2q.png',
	},
	aruni: {
		name: 'Aruni',
		safename: 'aruni',
		roles: ['Anti-Gadget', 'Anti-Entry'],
		side: 'defender',
		icon: 'https://i.imgur.com/PhCM38D.png',
	},
	zero: {
		name: 'Zero',
		safename: 'zero',
		roles: ['Anti-Gadget', 'Intel'],
		side: 'attacker',
		icon: 'https://i.imgur.com/87LCqv1.png',
	},
	ace: {
		name: 'Ace',
		safename: 'ace',
		roles: ['Anti-Gadget', 'Breach'],
		side: 'attacker',
		icon: 'https://i.imgur.com/GwWGSuu.png',
	},
	melusi: {
		name: 'Melusi',
		safename: 'melusi',
		roles: ['Crowd Control', 'Intel'],
		side: 'defender',
		icon: 'https://i.imgur.com/7BNXQnr.png',
	},
	oryx: {
		name: 'Oryx',
		safename: 'oryx',
		roles: ['Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/BdJnmYf.png',
	},
	iana: {
		name: 'Iana',
		safename: 'iana',
		roles: ['Intel', 'Front Line'],
		side: 'attacker',
		icon: 'https://i.imgur.com/bk77LOt.png',
	},
	wamai: {
		name: 'Wamai',
		safename: 'wamai',
		roles: ['Anti-Gadget', 'Trapper'],
		side: 'defender',
		icon: 'https://i.imgur.com/bFRCKTJ.png',
	},
	kali: {
		name: 'Kali',
		safename: 'kali',
		roles: ['Anti-Gadget', 'Support'],
		side: 'attacker',
		icon: 'https://i.imgur.com/sQGypuE.png',
	},
	amaru: {
		name: 'Amaru',
		safename: 'amaru',
		roles: ['Map Control', 'Front Line'],
		side: 'attacker',
		icon: 'https://i.imgur.com/m5u47Mw.png',
	},
	goyo: {
		name: 'Goyo',
		safename: 'goyo',
		roles: ['Anti-Entry', 'Trapper'],
		side: 'defender',
		icon: 'https://i.imgur.com/tYPrtCH.png',
	},
	nokk: {
		name: 'Nøkk',
		safename: 'nokk',
		roles: ['Front Line', 'Map Control'],
		side: 'attacker',
		icon: 'https://i.imgur.com/oleTyHs.png',
	},
	warden: {
		name: 'Warden',
		safename: 'warden',
		roles: ['Anti-Gadget', 'Intel', 'Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/HqTIR7x.png',
	},
	mozzie: {
		name: 'Mozzie',
		safename: 'mozzie',
		roles: ['Intel', 'Anti-Gadget'],
		side: 'defender',
		icon: 'https://i.imgur.com/yrFXGCn.png',
	},
	gridlock: {
		name: 'Gridlock',
		safename: 'gridlock',
		roles: ['Support', 'Map Control'],
		side: 'attacker',
		icon: 'https://i.imgur.com/WHkIm3H.png',
	},
	nomad: {
		name: 'Nomad',
		safename: 'nomad',
		roles: ['Front Line', 'Map Control'],
		side: 'attacker',
		icon: 'https://i.imgur.com/2I6OWIz.png',
	},
	kaid: {
		name: 'Kaid',
		safename: 'kaid',
		roles: ['Anti-Gadget', 'Anti-Entry', 'Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/Du1aa9i.png',
	},
	clash: {
		name: 'Clash',
		safename: 'clash',
		roles: ['Crowd Control', 'Intel', 'Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/eogGdHx.png',
	},
	maverick: {
		name: 'Maverick',
		safename: 'maverick',
		roles: ['Front Line', 'Breach'],
		side: 'attacker',
		icon: 'https://i.imgur.com/8hXt5z6.png',
	},
	maestro: {
		name: 'Maestro',
		safename: 'maestro',
		roles: ['Support', 'Anti-Gadget', 'Intel'],
		side: 'defender',
		icon: 'https://i.imgur.com/PQ8VBAF.png',
	},
	alibi: {
		name: 'Alibi',
		safename: 'alibi',
		roles: ['Intel', 'Trapper'],
		side: 'defender',
		icon: 'https://i.imgur.com/Phb6OUU.png',
	},
	lion: {
		name: 'Lion',
		safename: 'lion',
		roles: ['Intel', 'Map Control', 'Crowd Control'],
		side: 'attacker',
		icon: 'https://i.imgur.com/0zCtOUO.png',
	},
	finka: {
		name: 'Finka',
		safename: 'finka',
		roles: ['Front Line', 'Support'],
		side: 'attacker',
		icon: 'https://i.imgur.com/dxqOJu3.png',
	},
	vigil: {
		name: 'Vigil',
		safename: 'vigil',
		roles: ['Anti-Gadget', 'Crowd Control'],
		side: 'defender',
		icon: 'https://i.imgur.com/WkqMEZ6.png',
	},
	dokkaebi: {
		name: 'Dokkaebi',
		safename: 'dokkaebi',
		roles: ['Crowd Control', 'Intel'],
		side: 'attacker',
		icon: 'https://i.imgur.com/iVLOHr2.png',
	},
	zofia: {
		name: 'Zofia',
		safename: 'zofia',
		roles: ['Breach', 'Crowd Control', 'Anti-Gadget'],
		side: 'attacker',
		icon: 'https://i.imgur.com/AMOYwMJ.png',
	},
	ela: {
		name: 'Ela',
		safename: 'ela',
		roles: ['Crowd Control', 'Trapper'],
		side: 'defender',
		icon: 'https://i.imgur.com/OwjSJNB.png',
	},
	ying: {
		name: 'Ying',
		safename: 'ying',
		roles: ['Crowd Control', 'Front Line'],
		side: 'attacker',
		icon: 'https://i.imgur.com/BHUvTt4.png',
	},
	lesion: {
		name: 'Lesion',
		safename: 'lesion',
		roles: ['Anti-Entry', 'Trapper'],
		side: 'defender',
		icon: 'https://i.imgur.com/IvYOwrI.png',
	},
	mira: {
		name: 'Mira',
		safename: 'mira',
		roles: ['Support', 'Map Control'],
		side: 'defender',
		icon: 'https://i.imgur.com/gOnJqiF.png',
	},
	jackal: {
		name: 'Jackal',
		safename: 'jackal',
		roles: ['Map Control', 'Intel', 'Front Line'],
		side: 'attacker',
		icon: 'https://i.imgur.com/cGBKp2a.png',
	},
	hibana: {
		name: 'Hibana',
		safename: 'hibana',
		roles: ['Breach', 'Front Line'],
		side: 'attacker',
		icon: 'https://i.imgur.com/aqOOm2R.png',
	},
	echo: {
		name: 'Echo',
		safename: 'echo',
		roles: ['Intel', 'Crowd Control', 'Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/OMNe9qB.png',
	},
	caveira: {
		name: 'Caveira',
		safename: 'caveira',
		roles: ['Intel'],
		side: 'defender',
		icon: 'https://i.imgur.com/IeYRobc.png',
	},
	capitao: {
		name: 'Capitão',
		safename: 'capitao',
		roles: ['Map Control', 'Front Line'],
		side: 'attacker',
		icon: 'https://i.imgur.com/gBmMrMa.png',
	},
	blackbeard: {
		name: 'Blackbeard',
		safename: 'blackbeard',
		roles: ['Support'],
		side: 'attacker',
		icon: 'https://i.imgur.com/BOAh5x8.png',
	},
	valkyrie: {
		name: 'Valkyrie',
		safename: 'valkyrie',
		roles: ['Intel'],
		side: 'defender',
		icon: 'https://i.imgur.com/xJHdqA3.png',
	},
	buck: {
		name: 'Buck',
		safename: 'buck',
		roles: ['Front Line', 'Breach'],
		side: 'attacker',
		icon: 'https://i.imgur.com/u9slUlM.png',
	},
	frost: {
		name: 'Frost',
		safename: 'frost',
		roles: ['Crowd Control', 'Trapper'],
		side: 'defender',
		icon: 'https://i.imgur.com/FTbAE33.png',
	},
	mute: {
		name: 'Mute',
		safename: 'mute',
		roles: ['Anti-Gadget', 'Anti-Entry'],
		side: 'defender',
		icon: 'https://i.imgur.com/peaKoO1.png',
	},
	sledge: {
		name: 'Sledge',
		safename: 'sledge',
		roles: ['Anti-Gadget', 'Breach'],
		side: 'attacker',
		icon: 'https://i.imgur.com/JXV80ZY.png',
	},
	smoke: {
		name: 'Smoke',
		safename: 'smoke',
		roles: ['Support', 'Map Control'],
		side: 'defender',
		icon: 'https://i.imgur.com/aodW3TF.png',
	},
	thatcher: {
		name: 'Thatcher',
		safename: 'thatcher',
		roles: ['Support', 'Anti-Gadget'],
		side: 'attacker',
		icon: 'https://i.imgur.com/BuEp8mz.png',
	},
	ash: {
		name: 'Ash',
		safename: 'ash',
		roles: ['Front Line', 'Breach'],
		side: 'attacker',
		icon: 'https://i.imgur.com/ml0tMs3.png',
	},
	castle: {
		name: 'Castle',
		safename: 'castle',
		roles: ['Support', 'Map Control'],
		side: 'defender',
		icon: 'https://i.imgur.com/Fv8G4RW.png',
	},
	pulse: {
		name: 'Pulse',
		safename: 'pulse',
		roles: ['Intel'],
		side: 'defender',
		icon: 'https://i.imgur.com/Y2iDnWq.png',
	},
	thermite: {
		name: 'Thermite',
		safename: 'thermite',
		roles: ['Support', 'Breach'],
		side: 'attacker',
		icon: 'https://i.imgur.com/o896oL9.png',
	},
	montagne: {
		name: 'Montagne',
		safename: 'montagne',
		roles: ['Support'],
		side: 'attacker',
		icon: 'https://i.imgur.com/bzzVRTU.png',
	},
	twitch: {
		name: 'Twitch',
		safename: 'twitch',
		roles: ['Anti-Gadget', 'Front Line', 'Intel'],
		side: 'attacker',
		icon: 'https://i.imgur.com/jc5pPPK.png',
	},
	doc: {
		name: 'Doc',
		safename: 'doc',
		roles: ['Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/19gitiC.png',
	},
	rook: {
		name: 'Rook',
		safename: 'rook',
		roles: ['Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/UQK1UNc.png',
	},
	jager: {
		name: 'Jäger',
		safename: 'jager',
		roles: ['Anti-Gadget', 'Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/Y8EjdSy.png',
	},
	bandit: {
		name: 'Bandit',
		safename: 'bandit',
		roles: ['Anti-Gadget'],
		side: 'defender',
		icon: 'https://i.imgur.com/p6tWAW7.png',
	},
	blitz: {
		name: 'Blitz',
		safename: 'blitz',
		roles: ['Support'],
		side: 'attacker',
		icon: 'https://i.imgur.com/GxXncfV.png',
	},
	iq: {
		name: 'IQ',
		safename: 'iq',
		roles: ['Anti-Gadget', 'Front Line', 'Intel'],
		side: 'attacker',
		icon: 'https://i.imgur.com/M1NaKKv.png',
	},
	fuze: {
		name: 'Fuze',
		safename: 'fuze',
		roles: ['Crowd Control', 'Front Line'],
		side: 'attacker',
		icon: 'https://i.imgur.com/xsVA73Z.png',
	},
	glaz: {
		name: 'Glaz',
		safename: 'glaz',
		roles: ['Intel', 'Support'],
		side: 'attacker',
		icon: 'https://i.imgur.com/7vFvnxZ.png',
	},
	tachanka: {
		name: 'Tachanka',
		safename: 'tachanka',
		roles: ['Crowd Control', 'Support'],
		side: 'defender',
		icon: 'https://i.imgur.com/VTUCIZH.png',
	},
	kapkan: {
		name: 'Kapkan',
		safename: 'kapkan',
		roles: ['Trapper', 'Anti-Entry'],
		side: 'defender',
		icon: 'https://i.imgur.com/YHj9igl.png',
	},
};
